### ISSUE TITLE
Webpack --inline error when using engine-rn-web

### ISSUE THREAD

**Issue by pchmelar** [renative-org/renative#784] opened 2022-01-18 15:37 UTC
**Describe the bug**
Running `rnv run` on the latest version of RNV ends up with `Error: Unknown option '--inline'` when using `engine-rn-web`

**To Reproduce**

1. Run command `rnv new` and choose `renative-template-hello-world` template
2. In `renative.json` change the engine for web platform to `engine-rn-web`
3. Run command `rnv run -p web`
4. Observe error

**Expected behavior**
Webpack dev server starts up without any errors

**Screenshots or copy&paste**

![Screenshot 2022-01-18 at 16 25 49](https://user-images.githubusercontent.com/3842139/149966579-3c36f15d-21c4-47a0-815c-520b1802b5c6.png)

**Desktop**

-   OS: macOS 12.1 on M1 Pro
-   Node Version: 16.13.2
-   RNV Version: 0.34.0

**Additional context**
This is working as expected on RNV 0.31.3, so my guess is that 0.34.0 uses a newer version of Webpack with `--inline` removed. Seems like `inline` is now always true - [source](https://stackoverflow.com/questions/70528429/webpack-cli-error-webpack-cli-error-unknown-option-inline/70532911). So it should be enough to just remove it from `renative/packages/rnv-sdk-webpack/src/index.js`.

**Comment by andrew351** [comment] 2022-02-17 13:06
yeah also seems to happen whenever i use web engine

**Comment by kasinskas** [comment] 2022-02-17 13:09
Hey, rn-web is currently being worked on to run webpack 5, make it easier to override configs and assets, and fix all the issues currently existing on web/webos/tizen and other platforms that depend on this engine

**Comment by andrew351** [comment] 2022-02-17 21:07
> Hey, rn-web is currently being worked on to run webpack 5, make it easier to override configs and assets, and fix all the issues currently existing on web/webos/tizen and other platforms that depend on this engine. Will let you know when it's done

just a quick question, is there's a way to force use webpack 4 for now till the update comes ?

**Comment by kasinskas** [comment] 2022-03-01 11:29
0.36.0-canary.1 was released yesterday with webpack sdk updates, please try it out

**Comment by andrew351** [comment] 2022-03-01 14:02
> 0.36.0-canary.1 was released yesterday with webpack sdk updates, please try it out

I just tried it i made a fresh new project using rnv new and I got a new error upon running 

```
.../node_modules\webpack-cli\bin\prompt-command.js:108
                require(pathForCmd).default(...args); // eslint-disable-line
                                           ^

TypeError: Class constructor ServeCommand cannot be invoked without 'new'
```
Template: renative-template-hello-world@0.36.0-canary.1  
ReNative Version: 0.35.3

**Comment by kasinskas** [comment] 2022-03-01 14:13
You need to upgrade rnv to 0.36.0-canary.1 as well, not only the template

**Comment by andrew351** [comment] 2022-03-01 14:38
> You need to upgrade rnv to 0.36.0-canary.1 as well, not only the template

oh sorry my bad i removed rnv and installed it again and i thought it updated to canary version aswell , i just tested again so when i run at webos emulator the app launches into white screen and when i try windows with electron i get a few errors, i think this is not related to this issue do i open a new issue ?

```
Compiled with problems:X

ERROR in ./src/components/screenHome.js 44:60-69

export 'ICON_LOGO' (imported as 'ICON_LOGO') was not found in '../config' (possible exports: ROUTES, ThemeContext, ThemeProvider, default, hasFullScreenMenu, hasHorizontalMenu, hasMobileWebUI, hasVerticalMenu, hasWebFocusableUI, themeStyles)


ERROR in ./src/components/screenHome.js 46:10-31

export 'CONFIG' (imported as 'CONFIG') was not found in '../config' (possible exports: ROUTES, ThemeContext, ThemeProvider, default, hasFullScreenMenu, hasHorizontalMenu, hasMobileWebUI, hasVerticalMenu, hasWebFocusableUI, themeStyles)


ERROR in ./src/config.js 11:0-61

Module not found: Error: You attempted to import ../platformAssets/renative.runtime.json which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.


ERROR in ./src/config.js 12:0-47

Module not found: Error: You attempted to import ../platformAssets/runtime/fontManager which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.


ERROR in ./src/config.js 13:0-59

Module not found: Error: You attempted to import ../platformAssets/runtime/logo.png which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.


ERROR in ./node_modules/react-native-google-cast/index.js

Module build failed (from ./node_modules/@rnv/sdk-webpack/node_modules/babel-loader/lib/index.js):
SyntaxError: ...\node_modules\react-native-google-cast\index.js: Missing semicolon. (15:4)

  13 | export { CastButton }
  14 |
> 15 | type CastDevice = {
     |     ^
  16 |   id: string,
  17 |   version: string,
  18 |   name: string,
    at Parser._raise (...\node_modules\@babel\parser\src\parser\error.js:150:45)
    at Parser._raise [as raiseWithData] (...\node_modules\@babel\parser\src\parser\error.js:145:17)
    at Parser.raiseWithData [as raise] (...\node_modules\@babel\parser\src\parser\error.js:89:17)
    at Parser.raise [as semicolon] (...\node_modules\@babel\parser\src\parser\util.js:143:10)
    at Parser.semicolon [as parseExpressionStatement] (...\node_modules\@babel\parser\src\parser\statement.js:998:10)
    at Parser.parseExpressionStatement [as parseStatementContent] (...\node_modules\@babel\parser\src\parser\statement.js:477:19)
    at Parser.parseStatementContent [as parseStatement] (...\node_modules\@babel\parser\src\parser\statement.js:329:17)
    at Parser.parseStatement [as parseBlockOrModuleBlockBody] (...\node_modules\@babel\parser\src\parser\statement.js:1073:25)
    at Parser.parseBlockOrModuleBlockBody [as parseBlockBody] (...\node_modules\@babel\parser\src\parser\statement.js:1049:10)
    at Parser.parseBlockBody [as parseProgram] (...\node_modules\@babel\parser\src\parser\statement.js:214:10)

```

**Comment by kasinskas** [comment] 2022-03-01 15:38
Yes please, open a new one with the steps you did and I'll try to reproduce it. I did run windows on electron successfully, but maybe I missed something

**Comment by dotted** [comment] 2022-03-04 20:03
This problem has resurfaced in 0.36.0-canary.2. Installing hello-world template and trying to run it will reproduce the problem.

**Comment by kasinskas** [comment] 2022-03-05 21:26
Maybe canary.2 got out with old sdk-webpack files, since --inline is not used anymore. I just published canary.3 which also include electron and babel fixes, can you please try that one? I just ran it and seems okay

**Comment by dotted** [comment] 2022-03-05 21:33
Can confirm, canary.3 works

**Comment by mihaiblaga89** [comment] 2022-03-19 21:35
closing this for now. If there are any more issues feel free to reopen

**Closed by mihaiblaga89** 2022-03-19 21:35 UTC
Labels: bug, in review
