### ISSUE TITLE
renative-template-hello-world: TypeError when build the renative on both iOS and Android

### ISSUE THREAD

**Issue by an8h** [renative-org/renative#625] opened 2020-12-08 06:07 UTC
**Describe the bug**
I tried to follow the installation guide (https://renative.org/docs/intro-installation) to run renative on both iOS simulator and Android emulator using renative-template-hello-world. Once the bundle is ready and it tries to open the app I get a TypeError. 

**To Reproduce**

1. Run command 'rnv new'
2. Run command 'rnv run -p android'
3. See error (check Screenshots or copy&paste section)

4. Kill the process with 'Ctrl C'
5. Run command 'rnv run -p ios'
6. See error (check Screenshots or copy&paste section)

**Expected behavior**
Once the bundle is 100% ready and I don't get any errors in the terminal I would expect a running app on both iOS and Android. 

**Screenshots or copy&paste**
Android:
![Screenshot_1607406075](https://user-images.githubusercontent.com/15365380/101446205-1d1cd700-3923-11eb-95c6-001c287abe57.png)

iOS:
<img width="411" alt="Screenshot 2020-12-08 at 06 42 15" src="https://user-images.githubusercontent.com/15365380/101446225-25751200-3923-11eb-8f6b-9d22fbcbf3bf.png">

**Desktop (please complete the following information):**

-   OS: macOS Big Sur v.11.0.1
-   Node Version: v14.15.1
-   RNV Version: v 0.31.3 

**Additional context**
I tested renative-template-blank and it works.

**Comment by pavjacko** [comment] 2021-01-04 06:23
@an8h I've been trying to replicate above error but with no luck. 

one quick check (on android) could be to change `"enableHermes": false` in your renative.json and run app again with `rnv run -p android -r` . 
NOTE `-r` is important enabling/disabling hermes requires hard reset to take effect

Another option is to upgrade to upcoming release `npm i rnv@alpha -g` and try to create new app again.

If issue persist you could change `"reactNativeEngine": "default"`

I'll keep an eye on this error

**Comment by pauliusguzas** [comment] 2023-05-18 06:35
Could not reproduce this on latest rnv versions therefore closing, feel free to reopen again

**Closed by pauliusguzas** 2023-05-18 06:35 UTC
Labels: bug, pinned
